// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using standBY_prototype.DataAccess;

namespace standBY_prototype.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210809194851_BaseModelIdMigration")]
    partial class BaseModelIdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("standBY_prototype.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("classificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("cnpj")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_fundacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("quarentena")
                        .HasColumnType("bit");

                    b.Property<string>("razao_social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status_cliente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
